# Generated by Django 4.2.1 on 2023-06-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneDirection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='oneEvent',
        ),
    ]
